version: "3.8"

services:
  db:
    restart: always
    build: ./db/
    ports:
      - "5432:5432"
    container_name: db
  pipelines:
    build: .
    container_name: pipelines-zhidkov
    command: python pipeline.py --host 0.0.0.0 --port 5432
    volumes:
      - .:/pipelines/
    ports:
      - "8081:8081"


