
name: pipelinesDocker
on:
  push:
    branches:
      - main
jobs:
  pipelines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker compose up
      run: docker compose up -d
    - name: Docker logs
      run: docker compose logs -f -t
